package com.osahft.api.internal.assertion;

import com.osahft.api.model.ErrorResponse;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link ErrorResponse.ErrorResponseBuilder} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractErrorResponseErrorResponseBuilderAssert<S extends AbstractErrorResponseErrorResponseBuilderAssert<S, A>, A extends ErrorResponse.ErrorResponseBuilder> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractErrorResponseErrorResponseBuilderAssert}</code> to make assertions on actual ErrorResponse.ErrorResponseBuilder.
     *
     * @param actual the ErrorResponse.ErrorResponseBuilder we want to make assertions on.
     */
    protected AbstractErrorResponseErrorResponseBuilderAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
