package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailTransfer;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link MailTransfer.MailTransferBuilder} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractMailTransferMailTransferBuilderAssert<S extends AbstractMailTransferMailTransferBuilderAssert<S, A>, A extends MailTransfer.MailTransferBuilder> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractMailTransferMailTransferBuilderAssert}</code> to make assertions on actual MailTransfer.MailTransferBuilder.
     *
     * @param actual the MailTransfer.MailTransferBuilder we want to make assertions on.
     */
    protected AbstractMailTransferMailTransferBuilderAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
