package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailTransfer;
import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link MailTransfer.State} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractMailTransferStateAssert<S extends AbstractMailTransferStateAssert<S, A>, A extends MailTransfer.State> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractMailTransferStateAssert}</code> to make assertions on actual MailTransfer.State.
     *
     * @param actual the MailTransfer.State we want to make assertions on.
     */
    protected AbstractMailTransferStateAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
