package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailReceiverDownloadLinkMapping;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractMailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert<S extends AbstractMailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert<S, A>, A extends MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractMailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert}</code> to make assertions on actual MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder.
     *
     * @param actual the MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder we want to make assertions on.
     */
    protected AbstractMailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
