package com.osahft.api.internal.assertion;

import com.osahft.api.model.CreateMailTransferRequest;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link CreateMailTransferRequest.CreateMailTransferRequestBuilder} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractCreateMailTransferRequestCreateMailTransferRequestBuilderAssert<S extends AbstractCreateMailTransferRequestCreateMailTransferRequestBuilderAssert<S, A>, A extends CreateMailTransferRequest.CreateMailTransferRequestBuilder> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractCreateMailTransferRequestCreateMailTransferRequestBuilderAssert}</code> to make assertions on actual CreateMailTransferRequest.CreateMailTransferRequestBuilder.
     *
     * @param actual the CreateMailTransferRequest.CreateMailTransferRequestBuilder we want to make assertions on.
     */
    protected AbstractCreateMailTransferRequestCreateMailTransferRequestBuilderAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
