package com.osahft.api.internal.assertion;

import com.osahft.api.model.CreateMailTransferResponse;

/**
 * {@link CreateMailTransferResponse} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCreateMailTransferResponseAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class CreateMailTransferResponseAssert extends AbstractCreateMailTransferResponseAssert<CreateMailTransferResponseAssert, CreateMailTransferResponse> {

    /**
     * Creates a new <code>{@link CreateMailTransferResponseAssert}</code> to make assertions on actual CreateMailTransferResponse.
     *
     * @param actual the CreateMailTransferResponse we want to make assertions on.
     */
    public CreateMailTransferResponseAssert(CreateMailTransferResponse actual) {
        super(actual, CreateMailTransferResponseAssert.class);
    }

    /**
     * An entry point for CreateMailTransferResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCreateMailTransferResponse)</code> and get specific assertion with code completion.
     *
     * @param actual the CreateMailTransferResponse we want to make assertions on.
     * @return a new <code>{@link CreateMailTransferResponseAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CreateMailTransferResponseAssert assertThat(CreateMailTransferResponse actual) {
        return new CreateMailTransferResponseAssert(actual);
    }
}
