package com.osahft.api.internal.assertion;

import com.osahft.api.model.CreateMailTransferRequest;

/**
 * {@link CreateMailTransferRequest} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCreateMailTransferRequestAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class CreateMailTransferRequestAssert extends AbstractCreateMailTransferRequestAssert<CreateMailTransferRequestAssert, CreateMailTransferRequest> {

    /**
     * Creates a new <code>{@link CreateMailTransferRequestAssert}</code> to make assertions on actual CreateMailTransferRequest.
     *
     * @param actual the CreateMailTransferRequest we want to make assertions on.
     */
    public CreateMailTransferRequestAssert(CreateMailTransferRequest actual) {
        super(actual, CreateMailTransferRequestAssert.class);
    }

    /**
     * An entry point for CreateMailTransferRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCreateMailTransferRequest)</code> and get specific assertion with code completion.
     *
     * @param actual the CreateMailTransferRequest we want to make assertions on.
     * @return a new <code>{@link CreateMailTransferRequestAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CreateMailTransferRequestAssert assertThat(CreateMailTransferRequest actual) {
        return new CreateMailTransferRequestAssert(actual);
    }
}
