package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailReceiverDownloadLinkMapping;

/**
 * {@link MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractMailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert extends AbstractMailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert<MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert, MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder> {

    /**
     * Creates a new <code>{@link MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert}</code> to make assertions on actual MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder.
     *
     * @param actual the MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder we want to make assertions on.
     */
    public MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert(MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder actual) {
        super(actual, MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert.class);
    }

    /**
     * An entry point for MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myMailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder)</code> and get specific assertion with code completion.
     *
     * @param actual the MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder we want to make assertions on.
     * @return a new <code>{@link MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert assertThat(MailReceiverDownloadLinkMapping.MailReceiverDownloadLinkMappingBuilder actual) {
        return new MailReceiverDownloadLinkMappingMailReceiverDownloadLinkMappingBuilderAssert(actual);
    }
}
