package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailTransfer;

/**
 * {@link MailTransfer} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractMailTransferAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class MailTransferAssert extends AbstractMailTransferAssert<MailTransferAssert, MailTransfer> {

    /**
     * Creates a new <code>{@link MailTransferAssert}</code> to make assertions on actual MailTransfer.
     *
     * @param actual the MailTransfer we want to make assertions on.
     */
    public MailTransferAssert(MailTransfer actual) {
        super(actual, MailTransferAssert.class);
    }

    /**
     * An entry point for MailTransferAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myMailTransfer)</code> and get specific assertion with code completion.
     *
     * @param actual the MailTransfer we want to make assertions on.
     * @return a new <code>{@link MailTransferAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static MailTransferAssert assertThat(MailTransfer actual) {
        return new MailTransferAssert(actual);
    }
}
