package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailTransfer;

/**
 * {@link MailTransfer.State} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractMailTransferStateAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class MailTransferStateAssert extends AbstractMailTransferStateAssert<MailTransferStateAssert, MailTransfer.State> {

    /**
     * Creates a new <code>{@link MailTransferStateAssert}</code> to make assertions on actual MailTransfer.State.
     *
     * @param actual the MailTransfer.State we want to make assertions on.
     */
    public MailTransferStateAssert(MailTransfer.State actual) {
        super(actual, MailTransferStateAssert.class);
    }

    /**
     * An entry point for MailTransferStateAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myMailTransfer.State)</code> and get specific assertion with code completion.
     *
     * @param actual the MailTransfer.State we want to make assertions on.
     * @return a new <code>{@link MailTransferStateAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static MailTransferStateAssert assertThat(MailTransfer.State actual) {
        return new MailTransferStateAssert(actual);
    }
}
