package com.osahft.api.internal.assertion;

import com.osahft.api.document.MailTransfer;

/**
 * {@link MailTransfer.MailTransferBuilder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractMailTransferMailTransferBuilderAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class MailTransferMailTransferBuilderAssert extends AbstractMailTransferMailTransferBuilderAssert<MailTransferMailTransferBuilderAssert, MailTransfer.MailTransferBuilder> {

    /**
     * Creates a new <code>{@link MailTransferMailTransferBuilderAssert}</code> to make assertions on actual MailTransfer.MailTransferBuilder.
     *
     * @param actual the MailTransfer.MailTransferBuilder we want to make assertions on.
     */
    public MailTransferMailTransferBuilderAssert(MailTransfer.MailTransferBuilder actual) {
        super(actual, MailTransferMailTransferBuilderAssert.class);
    }

    /**
     * An entry point for MailTransferMailTransferBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myMailTransfer.MailTransferBuilder)</code> and get specific assertion with code completion.
     *
     * @param actual the MailTransfer.MailTransferBuilder we want to make assertions on.
     * @return a new <code>{@link MailTransferMailTransferBuilderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static MailTransferMailTransferBuilderAssert assertThat(MailTransfer.MailTransferBuilder actual) {
        return new MailTransferMailTransferBuilderAssert(actual);
    }
}
