package com.osahft.api.internal.assertion;

import com.osahft.api.model.SoftwareVersionInformation;

/**
 * {@link SoftwareVersionInformation} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractSoftwareVersionInformationAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class SoftwareVersionInformationAssert extends AbstractSoftwareVersionInformationAssert<SoftwareVersionInformationAssert, SoftwareVersionInformation> {

    /**
     * Creates a new <code>{@link SoftwareVersionInformationAssert}</code> to make assertions on actual SoftwareVersionInformation.
     *
     * @param actual the SoftwareVersionInformation we want to make assertions on.
     */
    public SoftwareVersionInformationAssert(SoftwareVersionInformation actual) {
        super(actual, SoftwareVersionInformationAssert.class);
    }

    /**
     * An entry point for SoftwareVersionInformationAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(mySoftwareVersionInformation)</code> and get specific assertion with code completion.
     *
     * @param actual the SoftwareVersionInformation we want to make assertions on.
     * @return a new <code>{@link SoftwareVersionInformationAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static SoftwareVersionInformationAssert assertThat(SoftwareVersionInformation actual) {
        return new SoftwareVersionInformationAssert(actual);
    }
}
